[package]
name = "pager"
version = "0.1.0"
authors = ["ticki <ticki@users.noreply.github.com>"]

[dependencies]
termion = { git = "https://github.com/redox-os/termion.git", branch = "redox_termios" }
